name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
          echo "❌ Docker credentials are missing!"
          exit 1
        fi
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

    - name: Build Docker Compose services
      run: docker compose -f docker-compose.yml build

    - name: List Docker images
      run: docker images

    - name: Tag Docker image
      run: docker tag advanced_pos_app:latest ${{ secrets.DOCKER_USERNAME }}/advanced_pos_app:latest

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/advanced_pos_app:latest
